create table dbo.IdiomasTextos
(
    IdiomaId nchar(2) not null,
    CreadoPorNombre nvarchar(100) not null,
    CreadoPorEtiqueta nvarchar(100) not null,
    CreadoFechaNombre nvarchar(100) not null,
    CreadoFechaEtiqueta nvarchar(100) not null,
    UltimaModificacionPorNombre nvarchar(100) not null,
    UltimaModificacionPorEtiqueta nvarchar(100) not null,
    UltimaModificacionFechaNombre nvarchar(100) not null,
    UltimaModificacionFechaEtiqueta nvarchar(100) not null,
    BorradoPorNombre nvarchar(100) not null,
    BorradoPorEtiqueta nvarchar(100) not null,
    BorradoFechaNombre nvarchar(100) not null,
    BorradoFechaEtiqueta nvarchar(100) not null,
    BorradoNombre nvarchar(100) not null,
    BorradoEtiqueta nvarchar(100) not null,
    BDNombre nvarchar(50) not null,
    EntidadesNombre nvarchar(50) not null,
    DatosNombre nvarchar(50) not null,
    NegocioNombre nvarchar(50) not null,
    WebPortalNombre nvarchar(50) not null,
    Repositorio nvarchar(50) not null,
    Agregar nvarchar(50) not null,
    Actualizar nvarchar(50) not null,
    Eliminar nvarchar(50) not null,
    MarcarComoBorrado nvarchar(50) not null,
    DesmarcarComoBorrado nvarchar(50) not null,
    Parametros nvarchar(50) not null,
    Propiedades nvarchar(50) not null,

    constraint PK_IdiomasTextos primary key clustered (IdiomaId),
    constraint FK_IdiomasTextos_IdiomaId foreign key (IdiomaId) references dbo.Idiomas (IdiomaId) on update cascade on delete cascade
)
go
